__title__ = 'cues'
__version__ = '0.2.0'
__author__ = 'Giovanni Salinas'
__author_email__ = 'gbs3@protonmail.com'
__description__ = 'Elegant and sophisticated prompts to inquire and ask questions at the command line.'
__url__ = 'https://github.com/GBS3/cues'
__license__ = 'MIT'
__copyright__ = 'Copyright 2021 Giovanni Salinas'
